---
- name: test if squid_port is set correctly
  assert:
    that:
      - squid_port is defined
      - squid_port | int
      - squid_port | int > 0
      - squid_port | int < 65536
    quiet: yes

- name: test if squid_cache_dir is set correctly
  assert:
    that:
      - squid_cache_dir is defined
      - squid_cache_dir | length > 0
      - squid_cache_dir.split(" ")[0] in ["ufs", "aufs", "diskd", "rock", "null"]
    quiet: yes

- name: test if squid_cache_dir is set correctly when no null driver is used
  assert:
    that:
      - squid_cache_dir.split(" ")[2] | int
      - squid_cache_dir.split(" ")[2] | int > 0
      - squid_cache_dir.split(" ")[3] | int
      - squid_cache_dir.split(" ")[3] | int > 0
      - squid_cache_dir.split(" ")[4] | int
      - squid_cache_dir.split(" ")[4] | int > 0
    quiet: yes
    fail_msg: "The null storage driver does not allow arguments to be set."
  when:
    - squid_cache_dir.split(" ")[0] != "null"
